### ISSUE TITLE
Potential import collision: import path should be "gopkg.in/h2non/gock.v1", not "github.com/h2non/gock"

### ISSUE THREAD

**Issue by KateGo520** [goodsru/go-universal-network-adapter#1]
## Background
The `h2non/gock` has already renamed it’s import path from "github.com/h2non/gock" to "gopkg.in/h2non/gock.v1".
As [README](https://github.com/h2non/gock/blob/v1.0.14/README.md) of `h2non/gock` v1.0.14 said, downstream repos should use "gopkg.in/h2non/gock.v1" to get or import `h2non/gock`.

```
Installation
> go get -u gopkg.in/h2non/gock.v1

Examples
See examples directory for more featured use cases.
Simple mocking via tests
package test
import (
  "github.com/nbio/st"
  "gopkg.in/h2non/gock.v1"
  "io/ioutil"
  "net/http"
  "testing"
)
…
```

But `goodsru/go-universal-network-adapter` still used the old path:
https://github.com/goodsru/go-universal-network-adapter/blob/master/Gopkg.toml#L45
```
[[constraint]]
  name = "github.com/h2non/gock"
  version = "1.0.14"
```
If you use this path to import `h2non/gock` into source code in the future, there may be some side effects.

## Solution
Replace all the old import paths, change `"github.com/h2non/gock"` to `"gopkg.in/h2non/gock.v1"`.
Where did you import it: https://github.com/goodsru/go-universal-network-adapter/search?q=github.com%2Fh2non%2Fgock&unscoped_q=github.com%2Fh2non%2Fgock

**Comment by KateGo520** [comment]
@dmitrymatviets  @MilovanovIvan  Could you help me review this issue? Thx :p

**Comment by MilovanovIvan** [comment]
Hi, @KateGo520!
Thnx for reporting, import paths replaced as you recommended.

**Comment by KateGo520** [comment]
Thanks for your efforts and feedback.
